books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # /books/
    path('', views.BooksModelView.as_view(), name = 'index'),
    # /books/book/
    path('book/', views.BookList.as_view(), name = 'book_list'),
    # /books/author/
    path('author/', views.AuthorList.as_view(), name = 'author_list'),
    # /books/publichser/
    path('publisher/', views.PublisherList.as_view(), name = 'publisher_list'),
    # /books/book/99
    path('book/<int:pk>/', views.BookDetail.as_view(), name = 'book_detail'),
    # /books/author/99
    path('author/<int:pk>', views.AuthorDetail.as_view(), name = 'author_detail'),
    # /books/publisher/99
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name = 'publisher_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views


# URL 패턴 매칭이 위에서 아래로 진행되므로, 순서에 유의 해야 함
# path() 함수는, route, view 2개의 필수 인자와 kwargs, name 2개의 선택 인자를 받음
#   route: URL 스트링
#   view: 호출되는 뷰 함수
#   kwargs: URL에서 추출된 파라미터 외에 추가적인 파라미터를 함수에 전달 할때 사용
#   name: 각 URL 패턴별로 이름을 붙여줌. 이 이름을 Templete 에서 많이 사용함.
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
    # path('polls/', views.index, name='index'),
    # path('polls/<int:question_id>/', views.detail, name='detail'),
    # path('polls/<int:question_id>/vote/',views.vote, name='vote'),
    # path('polls/<int:question_id>/results/',views.results, name='results'),

]

polls/urls.py
from django.urls import path
from . import views

# URL 패턴 매칭이 위에서 아래로 진행되므로, 순서에 유의 해야 함
# path() 함수는, route, view 2개의 필수 인자와 kwargs, name 2개의 선택 인자를 받음
#   route: URL 스트링
#   view: 호출되는 뷰 함수
#   kwargs: URL에서 추출된 파라미터 외에 추가적인 파라미터를 함수에 전달 할때 사용
#   name: 각 URL 패턴별로 이름을 붙여줌. 이 이름을 Templete 에서 많이 사용함.
# app_name 은, URL가 중복되는 경우 네임스페이스를 구별해 줌 (예를 들어, polls 애플리케이션과 임의의 blogs 라는 애플리케이션이 'detail' 이라는 url 패턴을 갖는 경우,)
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),                                # /polls/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),            # /polls/5/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),  # /polls/5/results
    path('<int:question_id>/vote/', views.vote, name='vote'),            # /polls/5/vote/
]

books/models.py
from django.db import models

# Create your models here.
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

polls/models.py
from django.db import models


# Create your models here.
# Question 테이블의 PK : 장고는 자동으로 Not Null & Autoincrement인 id 를 만들어 줌
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    # DateTimeField의 'date published' 는 pub_date에 대한 레이블 문구. Admin 사이트에서 볼 수 있음.
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    # 항상 인수로 전달된 테이블의 PK 와 연결됨. 실제 테이블에는 '_id' 라는 접미사가 붙음
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms

class VoteForm(forms.Form):
    choice = forms.ChoiceField()

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher

# Create your views here.

# 템플릿 뷰만 모델링하여 사용하는 경우 TemplateView 사용
class BooksModelView(TemplateView):
    # template_name 오버라이드 필수
    template_name = 'books/index.html'

    # 템플릿 파일에 넘겨줘야 할 데이터가 있는경우 get_context_data 오버라이드
    def get_context_data(self, **kwargs):
        # get_context_data를 오버라이드 할때는 반드시 첫줄에 super() 메소드를 호출해야 한다.
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context


class BookList(ListView):
    # model 테이블에 들어있는 모든 레코드를 가져와 구성하는 경우에는 테이블명만 지정해 주면 된다.
    # object_list 속성 자동구성
    # 템플릿 파일 모델명_list.html 자동구성
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

# pk로 조회해서 특정 객체를 가져오는 경우에는 테이블명만 명시 해주면 된다.
# 컨텍스트 변수로 object 를 자동으로 사용함
# 템플릿 파일을 모델명_detail.html 로 자동으로 사용함
class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

mysite/views.py
from django.views.generic.base import TemplateView
from django.apps import apps

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['app_list'] = ['polls','books']
        dictVerbose = {}
        for app in apps.get_app_configs():
            if 'site-packages' not in app.path:
                dictVerbose[app.label] = app.name

        context['verbose_dict'] = dictVerbose
        return context

polls/views.py
from django.shortcuts import render, get_object_or_404
from polls.models import Question, Choice
from django.http import HttpResponseRedirect, request
from django.urls import reverse
from django.views import generic

import logging

logger = logging.getLogger(__name__)
# logger = logging.getLogger(__name__)
# Create your views here.
# def index(request):
#     # Question 테이블 객체에서 pub_date 컬럼의 역순으로 정렬하여 5개의 최근 Question 객체를 가져옴
#     latest_question_list = Question.objects.all()
#     print(latest_question_list)
#     context = {'latest_question_list': latest_question_list}
#     # render() 는 context를 인자로 받아 HTTPResponse를 반환함
#     return render(request, 'polls/index.html', context)

class IndexView(generic.ListView):
    # 템플릿 파일명과 컨텍스트 변수명은 지정을 해도 되고, 디폴트 값을 사용 할 수도 있다.
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    # 테이블의 모든 데이터를 조회하려면 'model=Question' 만 해주면 되나, 더 자세한 쿼리를 하려면 get_queryset을 오버라이딩 해야함
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):

    logger.debug("vote().question_id: %s" % question_id)
    # logger.debug("vote().question_id: %s" % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 설문 투표 폼을 다시 보여준다
        return render(request, 'polls/detail.html',
                      {'question': question, 'error_message': "You didn't select a choice."})

    else:
        selected_choice.votes += 1
        selected_choice.save()
        # POST 데이터를 정상적으로 처리하였으면,
        # 항상 HttpResponseRedirect를 반환하여 리다리엑션 처리함
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

books/templates/books/author_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.salutation }}</p>
    <li>Email: {{ object.email }}</li>
{% endblock content %}

books/templates/books/author_list.html
{% extends "base_books.html" %}
{% block title %} Author List {% endblock title %}
{% block content %}
<h2>Author List</h2>
    <ul>
        {% for author in object_list %}
        <li><a href="{% url 'books:author_detail' author.id %}" >{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/books/book_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>
    <li>Authors:
        {% for author in object.authors.all %}
            {{ author }}
         {% if not forloop.last %},
         {% else %}
         {% endif %}
        {% endfor %}
    </li>
    <li>Publisher: {{ object.publisher }}</li>
    <li>Publication Date: {{ object.publication_date }}</li>
{% endblock content %}

books/templates/books/book_list.html
{% extends "base_books.html" %}
{% block title %} Book List {% endblock title %}
{% block content %}
<h2>Book List</h2>
    <ul>
        {% for book in object_list %}
        <li><a href="{% url 'books:book_detail' book.id %}" >{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/books/index.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in model_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{ modelname }}</a> </li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.website }}</p>
    <li>Address: {{ object.address }}</li>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}
{% block title %} Publisher List {% endblock title %}
{% block content %}
<h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
        <li><a href="{% url 'books:publisher_detail' publisher.id %}" >{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

polls/templates/polls/detail.html
{% extends 'base_polls.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!-- url 탬플릿 태그 사용, polls:vote는 URLconf 에서 적은 url 패턴 이름   -->
<form action="{% url 'polls:vote' question.id %}" method="post">
    <!--폼을 처리하는 경우, CSRF 공격을 방지하기 위한 기능-->
    {%csrf_token%}
    <!--vote() 뷰 함수에서 request.POST['choice'] 구문으로 액세스 할 수 있음-->
    <!--input 태그의 name, id 속성은 request.POST 사전에서 key, value 로 상돋됨-->
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br/>
    {% endfor %}
    <input type="submit" value = "Vote" />
</form>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'base_polls.html' %}

{% block content %}
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content %}

polls/templates/polls/results.html
{% extends 'base_polls.html' %}

{% block content %}
<h1>{{ quesiton.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.text}} - {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <meta charset="UTF-8">
    <title>{% block title %}My Amazing Site{% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a> </li>
            <li><a href="/admin/">Admin</a> </li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/base_books.html
{% extends 'base.html' %}

<title>{% block title %}Books Application Site{% endblock title %}</title>
{% block sidebar %}
    {{ block.super }}
    <ul>
        <li><a href="/books/">Books_Home</a></li>
    </ul>
{% endblock sidebar %}

templates/base_polls.html
{% extends 'base.html' %}

<title>{% block title %}Polls Application Site{% endblock title %}</title>
{% block sidebar %}
    {{ block.super }}
    <ul>
        <li><a href="/polls/">Polls_Home</a></li>
    </ul>
{% endblock sidebar %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>YMkim Django Application</h2>
    <ul>
        {% for key, value in verbose_dict.items %}
            {% with key|add:":"|add:"index" as urlvar %}
                <li><a href="{% url urlvar %}">{{ value }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}